apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: insuretech
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZbVY2WkdWc2JtbHhkV1U2WjJod1gxbzJVblZEUWpOTmJraG9Na2xGZEdrek9FRnJNemRKWVhWUFJEaEtOVEpyUTNGcGFRPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
