apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletestapp
  namespace: insuretech
  labels:
    app: scaletestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaletestapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: scaletestapp
    spec:
      containers:
      - name: scaletestapp
        image:  ghcr.io/yandex-practicum/scaletestapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
#        env:
#        - name: PORT
#          value: "8080"
#        - name: DB_CONNECTION_STRING
#          value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=disable"
#        envFrom:
#        - configMapRef:
#            name: insuretech-config
#        - secretRef:
#            name: insuretech-secrets
        resources:
          limits:
            cpu: "500m"
            memory: "30Mi"
          requests:
            cpu: "100m"
            memory: "30Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: scaletestapp
  namespace: insuretech
spec:
  selector:
    app: scaletestapp
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
